{
    'name': 'CMR New Recruitments',
    'version': '1.0',
    'summary': 'Customizions on new Recruitments',
    'depends': ['base', 'hr_recruitment', 'hr', 'survey', 'mail', 'hr_contract', ],
    'data': [
        'security/ir.model.access.csv',
        'security/hr_applicant_security.xml',
        'data/mail_data.xml',
        'data/mail_data_appointment.xml',
        'data/mail_data_direct.xml',
        'data/mail_data_appointment_direct.xml',
        'report/offer_letter.xml',
        'report/report_appointment_letter.xml',
        'report/offer_letter_direct.xml',
        'report/report_appointment_letter_direct.xml',
        'views/hr_applicant_views.xml',
        'views/hr_employee_views.xml',
        'views/employee_letter_views.xml',
        'views/grade_master_menu.xml',
        'views/check_list_views.xml',
        'views/survey_survey_views.xml',
        'views/hr_job_view.xml',
        'views/recruitment_application_report_views.xml',
        'views/hr_contract_view.xml',

    ],
    'installable': True,
    'application': False,
}
