{
    'name': 'NHCL Property Customise',
    'description': 'customise property management',
    'version': "1.0",
    'author': 'TechKhedut Inc.',
    'company': 'TechKhedut Inc.',
    'maintainer': 'TechKhedut Inc.',
    'website': "https://www.techkhedut.com",
    'category': 'Industry',
    'depends': ['rental_management', 'web', 'base', 'contacts', 'mail','purchase','purchase_requisition'],
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        'security/blanket_order_groups.xml',
        'data/email_template_data.xml',
        'data/invoice_mail.xml',
        'data/invoice_sequence.xml',
        'views/view_new_masters.xml',
        'views/view_property_details.xml',
        'views/view_base_models.xml',
        'views/view_account_move.xml',
        'views/inherit_tenancy_details.xml',
        'views/nhcl_maintenance_add.xml',
        'views/blanket_order.xml',
        'report/tenancy_details_report_template_customise.xml',
        'report/rent_invoice.xml',
        'report/purchase_order_landscape_custom.xml',
        'report/purchase_order_history.xml',
        'report/rent_invoice_without_header.xml',
    ],
    'license': 'OPL-1',
    'installable': True,
    'auto_install': False,
}
