{
    'name': 'NHCL Property Customise',
    'description': 'customise property management',
    'version': "1.0",
    'author': 'TechKhedut INC.',
    'company': 'TechKhedut Inc.',
    'maintainer': 'TechKhedut Inc.',
    'website': "https://www.techkhedut.com",
    'category': 'Industry',
    'depends': ['rental_management', 'web', 'base', 'contacts', 'mail', 'purchase', 'purchase_requisition'],
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        'security/blanket_order_groups.xml',
        'data/invoice_mail.xml',
        'data/invoice_sequence.xml',
        'views/view_new_masters.xml',
        'views/view_property_details.xml',
        'views/view_account_move.xml',
        'views/inherit_tenancy_details.xml',
        'views/nhcl_maintenance_add.xml',
        'views/blanket_order.xml',
        'wizard/rent_invoice_inherit.xml',
        'wizard/cam_invoice_report.xml',
        'wizard/uc_group.xml',
        'wizard/gas.xml',
        'report/rent_invoice_monthly.xml',
        'report/cam_report_all_data.xml',
        'report/uc_group_template.xml',
        'report/gas_report_template.xml',
        'report/tenancy_details_report_template_customise.xml',
        'report/rent_invoice.xml',
        'data/email_template_data.xml',
        'report/electric_report.xml',
        'report/purchase_order_landscape_custom.xml',
        'report/purchase_order_history.xml',
        'views/view_base_models.xml',
        'report/rent_invoice_without_header.xml',
        'views/category_view.xml',
        'views/electricbill.xml',
        'views/slab_master_views.xml',
    ],
    'license': 'OPL-1',
    'installable': True,
    'auto_install': False,
}
